# Generated by Django 5.0.4 on 2024-05-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp_rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
