# Generated by Django 5.0.4 on 2024-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp_rest', '0005_evaluation_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='infohome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
