# Generated by Django 5.0.4 on 2024-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp_rest', '0006_infohome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohome',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
